# FILE: jigu-app/build.ps1
# Jigu build script -- compiles a standalone Windows .exe using the in-box csc.exe.
# No Node, no Rust, no SDK required. This file is intentionally pure ASCII so that
# Windows PowerShell 5.1 (which reads .ps1 using the ANSI code page) parses it safely.
#
# Usage:  powershell -NoProfile -File build.ps1

$ErrorActionPreference = "Stop"
# Every path is derived from this script's own location, so the checkout can live anywhere.
# $PSScriptRoot is a reserved automatic variable and cannot be shadowed by host-injected
# variables, which is what the previous hardcoded block was guarding against.
if ([string]::IsNullOrEmpty($PSScriptRoot)) {
  throw "PSScriptRoot is empty -- run this with -File, not piped through stdin"
}
$root = $PSScriptRoot
$src  = Join-Path $root "src"
$web  = Join-Path $root "web"
$res  = Join-Path $root "resources"
$obj  = Join-Path $root "obj"
$dist = Join-Path $root "dist"
# Manifest-resource name of the installer payload (the zip built by New-PayloadZip below).
# The history shards travel as their own resource, Jigu.corpus.shards.zip.
$payloadResName = "Jigu.payload.zip"

# --- product version: single source of truth for the whole build ---
# Release CI reads this line to decide the tag / release name, and it is written into
# data_version.json + app_version.json below. It is ALSO compiled into the app and the
# installer via src\Version.g.cs (generated just below), so bumping this one line is all
# it takes -- AppVer.Number and SetupInfo.Version derive from it and must not be edited.
# Keep the line byte-identical: release.yml and tools\release.ps1 both regex it.
$version = "0.5.0"

# The icon file name carries the version on purpose: Windows caches icons by path, so a
# new version needs a new path or the user keeps seeing the old artwork. This string must
# match SetupInfo.IconFileName, which derives the same name from BuildInfo.Version --
# do not hand-write a third copy of it.
$iconName = "Jigu-$version.ico"

# The version used to be hand-mirrored into three C# constants, and forgetting one made
# the updater compare against a stale number and silently never fire. Generating a source
# file removes the chance entirely. Written before either csc invocation runs.
$verPath = Join-Path $src "Version.g.cs"
$verSrc = @"
// <auto-generated> generated by build.ps1 from `$version; do not edit by hand.
// Both the app and the installer compile this file (see the csc argument lists below).
namespace Jigu
{
    internal static class BuildInfo
    {
        public const string Version = "$version";
    }
}
"@
[System.IO.File]::WriteAllText($verPath, $verSrc, (New-Object System.Text.UTF8Encoding($false)))

# --- product naming (built from code points to keep this file ASCII-only) ---
$APP_CH  = [string][char]0x7A3D + [string][char]0x53E4          # "Ji Gu"
$appDir  = Join-Path $dist ([string][char]0x7A3D + [string][char]0x53E4)
$exeName = $APP_CH + ".exe"
$zipName = $APP_CH + "-portable.zip"
$readmeName = [string][char]0x4F7F + [string][char]0x7528 + [string][char]0x8BF4 + [string][char]0x660E + ".txt"

function Write-Step($t) { Write-Host ""; Write-Host "=== $t ===" -ForegroundColor Cyan }
function Write-Ok($t)   { Write-Host "  [OK] $t" -ForegroundColor Green }
function Write-Warn2($t){ Write-Host "  [!] $t" -ForegroundColor Yellow }

# Pack the staged files into ONE zip whose entry names are the payload keys (path relative
# to $appDir, forward slashes). Returns the zip path.
#
# The payload used to be generated as a base64 string literal per file. That costs 2.67x
# (literals are stored as UTF-16 in the assembly, measured) and -- the part that actually
# broke -- it is charged against csc's user-string heap, which is a hard ceiling. 0.4.0's
# CI build died on it: "fatal error CS0013 ... no logical space left to create more user
# strings". The payload had grown 877 KB because CI pulls the newest WebView2 SDK, and
# with the 45 MB shard resource in the same compilation that was enough. The same sources
# compile fine on a machine with the older DLLs -- exactly the "one parameter away" shape
# of the bug. The shards already avoid this by travelling as a /resource:; the payload now
# does too, so neither the SDK version nor the corpus size can push the compiler over.
function New-PayloadZip($files, $appDir, $zipPath) {
  $dir = Split-Path -Parent $zipPath
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  $zip = [System.IO.Compression.ZipFile]::Open($zipPath, [System.IO.Compression.ZipArchiveMode]::Create)
  try {
    foreach ($f in $files) {
      $rel = $f.FullName.Substring($appDir.Length + 1).Replace('\', '/')
      [void][System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, $f.FullName, $rel)
    }
  } finally { $zip.Dispose() }
  return $zipPath
}

# ---------------------------------------------------------------- 0. toolchain
Write-Step "0/6 locate in-box compiler and WebView2 runtime"
$csc = Join-Path $env:WINDIR "Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if (-not (Test-Path $csc)) { throw "csc.exe not found: $csc" }
Write-Ok "csc: $csc"

$wvCandidates = @(
  # CI / other machines: point this at an extracted Microsoft.Web.WebView2 NuGet package.
  # Release CI sets it, so a hosted runner needs no Office install.
  $env:JIGU_WEBVIEW2_DIR,
  # Repo-local: on a machine that has none of the office installs below,
  # dropping the two DLLs (plus WebView2Loader.dll) into <repo>\lib makes the build work.
  (Join-Path $PSScriptRoot "lib"),
  "C:\Program Files\Microsoft OfficePLUS\4.1.0.5753\addin",
  "C:\Program Files\Microsoft OfficePLUS\4.1.0.1926\addin",
  "C:\Program Files\Microsoft Office\root\Office16",
  "C:\Program Files\Microsoft Office\root\Office16\ADDINS\Microsoft Power Query for Excel Integrated\bin"
)
$wvDir = $null
foreach ($cand in $wvCandidates) {
  if ([string]::IsNullOrEmpty($cand)) { continue }
  if ((Test-Path (Join-Path $cand "Microsoft.Web.WebView2.Core.dll")) -and
      (Test-Path (Join-Path $cand "Microsoft.Web.WebView2.WinForms.dll"))) { $wvDir = $cand; break }
}
if (-not $wvDir) { throw "Microsoft.Web.WebView2.Core.dll not found on this machine" }
Write-Ok "WebView2 SDK: $wvDir"

$loaderCandidates = @(
  (Join-Path $PSScriptRoot "lib\WebView2Loader.dll"),
  "C:\Program Files\Microsoft OneDrive\26.163.0823.0004\WebView2Loader.dll",
  (Join-Path $wvDir "runtimes\win-x64\native\WebView2Loader.dll"),
  (Join-Path $wvDir "WebView2Loader.dll"),
  "C:\Program Files\Microsoft Office\root\Office16\WebView2Loader.dll",
  "C:\Program Files\Bambu Studio\WebView2Loader.dll"
)
$loader = $null
$bestVer = ""
foreach ($cand in $loaderCandidates) {
  if (-not (Test-Path $cand)) { continue }
  $ver = (Get-Item $cand).VersionInfo.FileVersion
  if ([string]::IsNullOrEmpty($bestVer)) { $loader = $cand; $bestVer = $ver; continue }
  $a = @(); foreach ($p in $ver.Split('.')) { $a += [int]$p }
  $b = @(); foreach ($p in $bestVer.Split('.')) { $b += [int]$p }
  while ($a.Count -lt 4) { $a += 0 }
  while ($b.Count -lt 4) { $b += 0 }
  for ($i = 0; $i -lt 4; $i++) {
    if ($a[$i] -gt $b[$i]) { $loader = $cand; $bestVer = $ver; break }
    if ($a[$i] -lt $b[$i]) { break }
  }
}
if (-not $loader) { throw "WebView2Loader.dll (x64) not found" }
Write-Ok ("WebView2 loader: " + $loader + "  v" + $bestVer)

# ---------------------------------------------------------------- 1. staging
Write-Step "1/6 clean old build output and icon cache, then stage assets"

# Remove obj / bin / previous outputs / previous icon files.
# Windows caches icons by file path, so stale builds or stale icon names can win.
foreach ($junk in @($obj,
                    "$root\bin",
                    "$root\Jigu.Assets.resources",
                    "$root\src\Jigu.resx",
                    (Join-Path $dist ($APP_CH + "-portable")))) {
  if (Test-Path -LiteralPath $junk) {
    Remove-Item -LiteralPath $junk -Recurse -Force -ErrorAction SilentlyContinue
  }
}
# Drop old icon files that lack a version suffix
try {
  Get-ChildItem -LiteralPath "$root\dist" -Recurse -ErrorAction SilentlyContinue |
    Where-Object { $_ -ne $null -and ($_.Name -eq "Jigu.ico" -or $_.Name -eq "app.ico") } |
    ForEach-Object { Remove-Item -LiteralPath $_.FullName -Force -ErrorAction SilentlyContinue }
} catch { }
Remove-Item -LiteralPath "$root\resources\app.ico" -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath "$root\resources\app.png" -Force -ErrorAction SilentlyContinue

# Regenerate the icon so every build carries the newest artwork.
# The child no longer gets -ExecutionPolicy Bypass: this script already runs under
# whatever policy the user chose, and sidestepping it for the child solves nothing.
if (Test-Path "$root\tools\make-icon.ps1") {
  & powershell -NoProfile -File "$root\tools\make-icon.ps1" | Out-Null
  Write-Ok "icon regenerated (resources\app.ico)"
}
if (-not (Test-Path "$root\resources\app.ico")) { throw "icon generation failed" }

# This used to also delete %LOCALAPPDATA%\IconCache.db and Explorer's iconcache* so that
# "the icon changed but the user still sees the old one" could not happen. Both reasons to
# stop doing that:
#   1. a build script has no business touching the user's shell-wide state -- it forces an
#      icon rebuild across the whole machine;
#   2. it is not needed any more: the icon file name carries the version (see $iconName
#      above), and a changed path invalidates Windows' per-path cache on its own. That is
#      the whole reason that name exists.

New-Item -ItemType Directory -Path $obj | Out-Null
# Older builds wrote the payload into this generated file as base64 string literals. It is
# no longer generated, and a stale copy left in the tree would collide with the Table() that
# now lives in src\PayloadExt.cs (CS0111: duplicate member). Delete it if it is still there.
$stalePayloadGen = Join-Path $src "InstallerPayload.g.cs"
if (Test-Path $stalePayloadGen) { Remove-Item $stalePayloadGen -Force }
if (Test-Path $appDir) { Remove-Item -Recurse -Force $appDir }
New-Item -ItemType Directory -Path $appDir | Out-Null
$dataDir = Join-Path $res "data"
New-Item -ItemType Directory -Path $dataDir -Force | Out-Null

$webFiles = @("index.html", "styles.css", "ink.css", "app.js")
foreach ($f in $webFiles) {
  $from = Join-Path $web $f
  if (-not (Test-Path $from)) { throw "missing web asset: $from" }
}
Write-Ok "web assets found"

$utf8 = New-Object System.Text.UTF8Encoding($false)
$sha = [System.Security.Cryptography.SHA256]::Create()


# ---------------------------------------------------------------- 2. resources
Write-Step "2/6 embed assets as generated C# source (deterministic, no resource lookup)"
# Previous builds used ResourceWriter + ResourceManager, but ResourceManager could
# not retrieve the entries at runtime (GetObject returned null), leaving the memory
# index empty and making WebView2 report ERR_FILE_NOT_FOUND. Assets are now compiled
# in as base64 string constants: no resource lookup, no disk access, nothing to fail.
# ---- embedded seed: first book only, as an offline fallback ----
# MUST run before the asset loop below reads resources\seed.json: this refresh used to sit
# further down, so the first build after a book edit embedded the PREVIOUS version of the
# seed while the shipped corpus.json already carried the new one.
$seedSrc = Join-Path $dataDir ("00_" + [string][char]0x79CD + [string][char]0x5B50 + ".json")
if (Test-Path $seedSrc) {
  Copy-Item $seedSrc (Join-Path $res "seed.json") -Force
  Write-Ok "embedded seed prepared (offline fallback only)"
}

$assetList = New-Object System.Collections.ArrayList
[void]$assetList.Add(@("index.html",     (Join-Path $web "index.html")))
[void]$assetList.Add(@("styles.css",     (Join-Path $web "styles.css")))
[void]$assetList.Add(@("ink.css",        (Join-Path $web "ink.css")))
[void]$assetList.Add(@("app.js",         (Join-Path $web "app.js")))
[void]$assetList.Add(@("app.png",        (Join-Path $res "app.png")))
# Only the seed corpus is embedded, purely as an offline fallback when corpus.json is absent.
[void]$assetList.Add(@("seed.json",      (Join-Path $res "seed.json")))
# The label table is the bridge between the user language and the corpus annotation.
# Embedded as a fallback; an external labels.json next to the exe takes precedence.
[void]$assetList.Add(@("labels.json",     (Join-Path $res "labels.json")))
# Query-side stopwords: modern function words rare in a classical corpus, so IDF
# over-rewards them. Same external-first fallback as the label table.
[void]$assetList.Add(@("stopwords.json",  (Join-Path $res "stopwords.json")))
# Self-check expectations are embedded too: --selfcheck must be able to assert recall
# quality on a RELEASE build, where the tests\ folder is not shipped. A guardrail that
# silently skips itself is worse than no guardrail.
[void]$assetList.Add(@("selfcheck-cases.json", (Join-Path $root "tests\cases.json")))


$gen = New-Object System.Text.StringBuilder
[void]$gen.AppendLine("// <auto-generated> generated by build.ps1: embedded assets (base64)")
[void]$gen.AppendLine("// do not edit by hand; sources live in web\ and resources\.")
[void]$gen.AppendLine("// </auto-generated>")
[void]$gen.AppendLine("using System;")
[void]$gen.AppendLine("using System.Collections.Generic;")
[void]$gen.AppendLine("")
[void]$gen.AppendLine("namespace Jigu")
[void]$gen.AppendLine("{")
[void]$gen.AppendLine("    /// <summary>compiled-in asset table: relative path -> base64</summary>")
[void]$gen.AppendLine("    internal static class EmbeddedAssets")
[void]$gen.AppendLine("    {")
[void]$gen.AppendLine("        public static Dictionary<string, string> Table()")
[void]$gen.AppendLine("        {")
[void]$gen.AppendLine("            Dictionary<string, string> t = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);")
$totalBytes = 0
$webCount = 0
$dataCount = 0
foreach ($pair in $assetList) {
  if (-not (Test-Path -LiteralPath $pair[1])) { throw ("missing asset: " + $pair[1]) }
  $bytes = [System.IO.File]::ReadAllBytes($pair[1])
  $totalBytes += $bytes.Length
  # UI assets come from web\, everything else (corpus, the two tables, selfcheck cases,
  # icon source) counts as data. Count these for real: the log line used to hardcode
  # "web=8", which matched nothing, and a build log you cannot trust costs you the first
  # clue when an asset fails to make it into the binary.
  if ($pair[1].StartsWith($web, [StringComparison]::OrdinalIgnoreCase)) { $webCount++ }
  else { $dataCount++ }
  $b64 = [Convert]::ToBase64String($bytes)
  [void]$gen.AppendLine("            t[""" + $pair[0] + """] = """ + $b64 + """;")
}
[void]$gen.AppendLine("            return t;")
[void]$gen.AppendLine("        }")
[void]$gen.AppendLine("    }")
[void]$gen.AppendLine("}")
# ---- Merge all book files into ONE external corpus.json (data lives OUTSIDE the exe) ----
$corpusPath = Join-Path $appDir "corpus.json"
$corpusSb = New-Object System.Text.StringBuilder
[void]$corpusSb.Append('{"book":"corpus","items":[')
$firstDoc = $true
$totalDocs = 0
$dataFiles = Get-ChildItem -Path $dataDir -Filter *.json | Sort-Object Name

# Pass 1: collect every record together with its original text.
$all = New-Object System.Collections.ArrayList
$rawDocs = 0
foreach ($file in $dataFiles) {
  if ($file.Name -eq "version.json") { continue }
  $obj = [System.IO.File]::ReadAllText($file.FullName, $utf8) | ConvertFrom-Json
  $bookName = $obj.book
  $count = 0
  foreach ($it in $obj.items) {
    # pros/cons carry the authored pros-and-cons analysis shown in the UI panel.
    $rec = [ordered]@{
      book = $bookName; chapter = $it.chapter; title = $it.title
      original = $it.original; translation = $it.translation
      figures = $it.figures; decision = $it.decision; outcome = $it.outcome; themes = $it.themes
      pros = $it.pros; cons = $it.cons
    }
    # The annotation fields are copied through only when the record actually carries them.
    # Assigning them unconditionally would emit "verdict": null for every unannotated
    # record, and a null where the reader expects a string is a different thing from a
    # missing key -- the shards ship the two forms side by side, so corpus.json must too.
    if ($it.cast)         { $rec["cast"] = $it.cast }
    if ($it.cause)        { $rec["cause"] = $it.cause }
    if ($it.process)      { $rec["process"] = $it.process }
    if ($it.significance) { $rec["significance"] = $it.significance }
    if ($it.verdict)      { $rec["verdict"] = $it.verdict; $rec["verdictWhy"] = $it.verdictWhy }
    [void]$all.Add(@([string]$it.original, $rec))
    $count++; $rawDocs++
  }
  Write-Host ("     {0,-12} {1,4} docs" -f $bookName, $count)
}

# Pass 2: drop records whose original text repeats a later one.
# The seed volume (00_...) sorts first and overlaps the period volumes, so "keep the last
# occurrence" keeps the period-volume copy, whose book attribution is the accurate one.
# Left alone, duplicates eat two of the three result slots for the same event.
# The seed FILE is untouched: it doubles as the embedded offline fallback.
$keep = New-Object "bool[]" $all.Count
$seenOrig = @{}
for ($i = $all.Count - 1; $i -ge 0; $i--) {
  $key = [string]$all[$i][0]
  if ($key.Length -eq 0) { $keep[$i] = $true; continue }
  if ($seenOrig.ContainsKey($key)) { continue }
  $seenOrig[$key] = 1
  $keep[$i] = $true
}
$skipped = 0
for ($i = 0; $i -lt $all.Count; $i++) {
  if (-not $keep[$i]) { $skipped++; continue }
  if (-not $firstDoc) { [void]$corpusSb.Append(',') }
  $firstDoc = $false
  [void]$corpusSb.Append(($all[$i][1] | ConvertTo-Json -Depth 6 -Compress))
  $totalDocs++
}
[void]$corpusSb.Append(']}')
[System.IO.File]::WriteAllText($corpusPath, $corpusSb.ToString(), $utf8)
$corpusHash = ($sha.ComputeHash([System.IO.File]::ReadAllBytes($corpusPath)) | ForEach-Object { $_.ToString('x2') }) -join ''
Write-Ok ("external corpus: " + $totalDocs + " docs, " + [math]::Round((Get-Item $corpusPath).Length/1KB,1) + " KB")
if ($skipped -gt 0) {
  Write-Warn2 ("deduped " + $skipped + " record(s) repeating an original text (" + $rawDocs + " raw -> " + $totalDocs + ")")
}

# ---- data_version.json next to the exe ----
# "files" are plain-file replacements: downloaded and written as-is, not merged by book.
# labels.json / stopwords.json live here so both tables can be extended without a new build.
$synPath = Join-Path $res "labels.json"
$synHash = (Get-FileHash -LiteralPath $synPath -Algorithm SHA256).Hash.ToLowerInvariant()
$stopPath = Join-Path $res "stopwords.json"
$stopHash = (Get-FileHash -LiteralPath $stopPath -Algorithm SHA256).Hash.ToLowerInvariant()
$dv = [ordered]@{
  version = $version
  generated_at = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
  source_url = "https://github.com/1279255198psy/jigu-app"
  books = [ordered]@{ corpus = $corpusHash }
  files = [ordered]@{ "labels.json" = $synHash; "stopwords.json" = $stopHash }
  paths = [ordered]@{ corpus = "corpus.json"; "labels.json" = "labels.json"; "stopwords.json" = "stopwords.json" }
}
[System.IO.File]::WriteAllText((Join-Path $appDir "data_version.json"), ($dv | ConvertTo-Json -Depth 5), $utf8)
Write-Ok "data_version.json written"

# ---- app_version.json templates (for the developer to host) ----
$appPkg = [string][char]0x7A3D + [string][char]0x53E4 + "-setup.exe"
$avExample = [ordered]@{
  version = $version; url = ("https://example.com/jigu/" + $appPkg); sha256 = ""
  notes = "External corpus with inverted index; dual-track hot update; OS self-adaptation."
  mandatory = $false
}
[System.IO.File]::WriteAllText((Join-Path $appDir "app_version.example.json"),
  ($avExample | ConvertTo-Json -Depth 4), $utf8)
Write-Ok "app_version example written"
$genPath = "$root\src\EmbeddedAssets.g.cs"
[System.IO.File]::WriteAllText($genPath, $gen.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Ok ("assets embedded: web=" + $webCount + " data=" + $dataCount + " total=" + [math]::Round($totalBytes/1KB,1) + " KB")
Write-Ok ("generated source: " + $genPath + " (" + [math]::Round((Get-Item $genPath).Length/1KB,1) + " KB)")

# ---------------------------------------------------------------- 3. compile
Write-Step "3/6 compile the executable"
$cscArgs = @(
  "/nologo", "/target:winexe", "/platform:anycpu", "/optimize+", "/utf8output",
  ("/out:" + (Join-Path $appDir $exeName)),
  "/reference:System.dll",
  "/reference:System.Core.dll",
  "/reference:System.Drawing.dll",
  "/reference:System.Windows.Forms.dll",
  "/reference:System.Net.dll",
  "/reference:System.Security.dll",
  # PayloadExt.ExtractShards uses ZipArchive; the assembly ships with .NET 4.5+ in the box.
  "/reference:System.IO.Compression.dll",
  ("/reference:" + (Join-Path $wvDir "Microsoft.Web.WebView2.Core.dll")),
  ("/reference:" + (Join-Path $wvDir "Microsoft.Web.WebView2.WinForms.dll"))
)
$iconPath = Join-Path $res "app.ico"
if (Test-Path $iconPath) { $cscArgs += ("/win32icon:" + $iconPath) }
# Without a supportedOS manifest, Environment.OSVersion reports 6.2.9200 (Windows 8)
# on Windows 10/11, and the self-check report shows that wrong string to users.
$manifestPath = Join-Path $res "app.manifest"
if (Test-Path $manifestPath) { $cscArgs += ("/win32manifest:" + $manifestPath) }
else { throw ("manifest missing: " + $manifestPath) }
# Compile every C# source in src\ (Host.cs, Corpus.cs, Json.cs, Update.cs) plus the
# generated asset tables, so new modules are picked up automatically.
Get-ChildItem -Path $src -Filter *.cs | Sort-Object Name | ForEach-Object {
  # Exclude the installer sources (they define their own Main) and the generated
  # *.g.cs tables, which are appended explicitly below.
  $skip = ($_.Name -eq "Installer.cs") -or ($_.Name -eq "SetupAssemblyInfo.cs") -or ($_.Name.EndsWith(".g.cs"))
  if (-not $skip) {
    $cscArgs += $_.FullName
  }
}
# ---- Stage the runtime files BEFORE compiling, so the embedded payload (below) is complete ----
Copy-Item (Join-Path $wvDir "Microsoft.Web.WebView2.Core.dll")     $appDir -Force
Copy-Item (Join-Path $wvDir "Microsoft.Web.WebView2.WinForms.dll") $appDir -Force
Copy-Item $loader (Join-Path $appDir "WebView2Loader.dll") -Force
$portableData = Join-Path $appDir "data"
New-Item -ItemType Directory -Path $portableData -Force | Out-Null
# Keep the delivered folder clean: drop runtime caches and stale artifacts that must never
# ship with the product (they are recreated on the user's machine as needed).
foreach ($junk in @("jigu-data", "pending", "version.json", "selftest.txt", "update-sim-report.txt", "jigu-debug.log", "app_version.test.json", "app_version.example.json", $readmeName)) {
  $p = Join-Path $appDir $junk
  if (Test-Path -LiteralPath $p) { Remove-Item -LiteralPath $p -Recurse -Force -ErrorAction SilentlyContinue }
}
# Icons left by the previous version: the name carries the version, so every release adds
# a new one. Sweep away everything except the current name so old artwork cannot ship.
Get-ChildItem -LiteralPath $appDir -Filter "Jigu-*.ico" -File -ErrorAction SilentlyContinue |
  Where-Object { $_.Name -ne $iconName } |
  ForEach-Object { Remove-Item -LiteralPath $_.FullName -Force -ErrorAction SilentlyContinue }
# Merge the per-book JSON into the external corpus later (corpus.json is the runtime source
# of truth); data\ is still shipped as an editable reference set for the user.
Copy-Item (Join-Path $dataDir "*") $portableData -Recurse -Force
# Readme for the end user (UTF-8 source copied verbatim; literal Chinese name).
Copy-Item "$root\resources\readme-installed.txt" (Join-Path $appDir $readmeName) -Force
Copy-Item "$root\resources\app.ico" (Join-Path $appDir $iconName) -Force
# The update source, one line. Two forms are accepted by UpdateSource:
#   github:owner/repo   -> read the repo's latest GitHub Release assets (the default below)
#   https://... / file://... -> static base URL (self-hosted mirror, network share, offline test)
# Written BEFORE the payload is generated so both the installer and the hot-swap path ship it.
# ExtractTo deliberately will NOT overwrite these two files if they already exist in the
# target directory, so a distributor's or user's custom source survives auto-updates.
$updateSrc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $appDir "update_base.txt"),
  "github:1279255198psy/jigu-app", $updateSrc)
# data_base.txt overrides the data channel only; same value here means "follow the app source".
[System.IO.File]::WriteAllText((Join-Path $appDir "data_base.txt"),
  "github:1279255198psy/jigu-app", $updateSrc)
# ---- Stage the history shards: <appDir>\corpus\* ----
# Produced by tools/convert-24histories (see build\corpus). They are NOT part of the base64
# payload: a string literal round-trips through UTF-16 in the assembly, so base64 costs 2.67x
# here (measured) -- 20 MB of shards would add ~55 MB to the installer. They travel as a
# compressed manifest resource instead (see /resource: on the setup compile below).
$shardSrc = Join-Path $root "build\corpus"
$shardDst = Join-Path $appDir "corpus"
$shardZip = Join-Path $root "build\corpus.shards.zip"
$shardCount = 0
if (Test-Path $shardSrc) {
  if (Test-Path $shardDst) { Remove-Item $shardDst -Recurse -Force }
  New-Item -ItemType Directory -Path $shardDst -Force | Out-Null
  Copy-Item (Join-Path $shardSrc "*") $shardDst -Recurse -Force
  $shardCount = (Get-ChildItem $shardDst -Recurse -File | Measure-Object).Count
  if (Test-Path $shardZip) { Remove-Item $shardZip -Force }
  Add-Type -AssemblyName System.IO.Compression.FileSystem
  [System.IO.Compression.ZipFile]::CreateFromDirectory($shardDst, $shardZip)
  Write-Ok ("history shards: " + $shardCount + " files, " + [math]::Round((Get-Item $shardZip).Length/1KB,1) + " KB compressed")
} else {
  Write-Warn2 ("history shards missing: " + $shardSrc + " -- run tools/convert-24histories to include them (building without)")
}
Write-Ok ("staged runtime files: " + (Get-ChildItem $appDir -Recurse -File).Count + " files")
$cscArgs += $genPath
$cscArgs += $verPath
# The app also carries the installer payload: hot update needs the CURRENT exe to be able to
# unpack a newly downloaded release (--extract-to). Generated before this compile so it is
# always in sync with the files staged above.
# corpus\ is excluded on purpose: the shards ship as a compressed /resource: instead of
# base64 string literals, which would cost 2.67x (see the staging step above).
$payloadFiles = Get-ChildItem -Path $appDir -Recurse -File |
  Where-Object { $_.FullName.Substring($appDir.Length + 1) -notlike "corpus\*" } |
  Sort-Object FullName
$plBytes = ($payloadFiles | Measure-Object -Property Length -Sum).Sum
# Join from $root, not from $obj: the corpus merge below reassigns $obj to a parsed JSON
# document, so the top-of-file $obj directory is long gone by the time we get here.
$payloadAppZip = New-PayloadZip $payloadFiles $appDir (Join-Path $root "obj\payload.app.zip")
Write-Ok ("embedded payload: " + $payloadFiles.Count + " files, " + [math]::Round($plBytes/1KB,1) + " KB -> " + [math]::Round((Get-Item $payloadAppZip).Length/1KB,1) + " KB as a resource")
$cscArgs += ("/resource:" + $payloadAppZip + "," + $payloadResName)
# This pass embeds a payload WITHOUT the app exe, because appDir has no exe yet. Once the
# app is compiled the zip is rebuilt with a complete payload for the setup wizard
# (see "Rebuild the payload" below).
# Note the /resource: line above: the payload IS part of the app build. The
# comment that used to sit here claimed "InstallerPayload.g.cs is intentionally NOT part of
# the app build" -- the exact opposite, a leftover from before the two-pass scheme. Removed.
#
# Open question: the hot-swap writer is the INSTALLER (RunReplace spawns newExePath), and
# docs only ever describe --extract-to on the setup exe. That leaves the payload baked
# into the app itself (and AppMain's matching --extract-to branch) with no caller we can
# find; it may be dead weight. Kept as-is until that is settled -- it costs size, not
# correctness.

$cscOut = & $csc $cscArgs 2>&1
$cscOut | ForEach-Object { Write-Host "     $_" }
if ($LASTEXITCODE -ne 0) { throw ("compile failed, csc exit " + $LASTEXITCODE) }
Write-Ok ("compiled: " + (Join-Path $appDir $exeName))
# ---- Rebuild the payload now that the app exe exists, so the setup wizard and the
# hot-swap path carry a COMPLETE release (including the executable itself) ----
# corpus\ is excluded on purpose: the shards ship as a compressed /resource: of their own.
$payloadFiles = Get-ChildItem -Path $appDir -Recurse -File |
  Where-Object { $_.FullName.Substring($appDir.Length + 1) -notlike "corpus\*" } |
  Sort-Object FullName
$plBytes = ($payloadFiles | Measure-Object -Property Length -Sum).Sum
$payloadSetupZip = New-PayloadZip $payloadFiles $appDir (Join-Path $root "obj\payload.setup.zip")
$hasExe = ($payloadFiles | Where-Object { $_.Name -like "*.exe" }).Count
Write-Ok ("final payload: " + $payloadFiles.Count + " files (exe=" + $hasExe + "), " + [math]::Round($plBytes/1KB,1) + " KB -> " + [math]::Round((Get-Item $payloadSetupZip).Length/1KB,1) + " KB as a resource")


# ---------------------------------------------------------------- 4. package
Write-Step "4/6 assemble the portable folder"
Copy-Item (Join-Path $wvDir "Microsoft.Web.WebView2.Core.dll")     $appDir -Force
Copy-Item (Join-Path $wvDir "Microsoft.Web.WebView2.WinForms.dll") $appDir -Force
Copy-Item $loader (Join-Path $appDir "WebView2Loader.dll") -Force
Write-Ok "WebView2 runtime files bundled"

$portableData = Join-Path $appDir "data"
New-Item -ItemType Directory -Path $portableData -Force | Out-Null
# Keep the delivered folder clean: drop runtime caches and stale artifacts that must never
# ship with the product (they are recreated on the user's machine as needed).
foreach ($junk in @("jigu-data", "pending", "version.json", "selftest.txt", "update-sim-report.txt", "jigu-debug.log", "app_version.test.json", "app_version.example.json", $readmeName)) {
  $p = Join-Path $appDir $junk
  if (Test-Path -LiteralPath $p) { Remove-Item -LiteralPath $p -Recurse -Force -ErrorAction SilentlyContinue }
}
# Icons left by the previous version: the name carries the version, so every release adds
# a new one. Sweep away everything except the current name so old artwork cannot ship.
Get-ChildItem -LiteralPath $appDir -Filter "Jigu-*.ico" -File -ErrorAction SilentlyContinue |
  Where-Object { $_.Name -ne $iconName } |
  ForEach-Object { Remove-Item -LiteralPath $_.FullName -Force -ErrorAction SilentlyContinue }
# The per-book JSON stays alongside the merged corpus.json: corpus.json is what the engine
# reads at runtime, while data\ is an editable reference set for the user.
Copy-Item (Join-Path $dataDir "*") $portableData -Recurse -Force
# Readme for the end user (UTF-8 source copied verbatim; literal Chinese name).
Copy-Item "$root\resources\readme-installed.txt" (Join-Path $appDir $readmeName) -Force
$countData = (Get-ChildItem $portableData -Recurse -Filter *.json | Measure-Object).Count
Write-Ok ("corpus files bundled: " + $countData)

# (data_base.txt is written earlier, next to update_base.txt, so it makes it into the
#  installer payload -- it used to be written here, AFTER the payload was generated, which
#  meant only the portable zip carried it.)


# ---------------------------------------------------------------- 5. zip
Write-Step "5/6 create the portable zip"
$zip = Join-Path $dist $zipName
if (Test-Path $zip) { Remove-Item $zip -Force }
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory($appDir, $zip)
Write-Ok ("zip: " + $zip)

# ---------------------------------------------------------------- 6. installer
Write-Step "6/6 build the Windows installer (setup wizard)"
# Inno Setup is not available on this machine and the sandbox has no network, so the
# installer is produced with the same in-box csc.exe. It provides an equivalent
# experience: Chinese wizard, per-user default path, desktop + start menu shortcuts,
# uninstall entry in Windows Settings, and a silent mode used for automated testing.
$iconInApp = Join-Path $appDir $iconName
Copy-Item "$root\resources\app.ico" $iconInApp -Force
Write-Ok "app icon placed for shortcuts and uninstall entry"

# Installer payload: every file of the portable folder (so nothing is missed)
# Reuse the payload generated in step 3 (it already contains every staged file, including
# the freshly compiled exe, so the wizard and the hot-swap path stay in sync).
Write-Ok ("installer payload reused: " + $payloadFiles.Count + " files, " + [math]::Round($plBytes/1KB,1) + " KB")

$setupName = $APP_CH + "-" + [string][char]0x5B89 + [string][char]0x88C5 + [string][char]0x5305 + ".exe"
$setupPath = Join-Path $dist $setupName
if (Test-Path $setupPath) { Remove-Item $setupPath -Force }
$setupArgs = @(
  "/nologo", "/target:winexe", "/platform:anycpu", "/optimize+", "/utf8output",
  ("/out:" + $setupPath),
  ("/win32icon:" + $iconInApp),
  ("/win32manifest:" + (Join-Path $res "app.manifest")),
  "/reference:System.dll",
  "/reference:System.Core.dll",
  "/reference:System.Drawing.dll",
  "/reference:System.Windows.Forms.dll",
  "/reference:System.IO.Compression.dll"
)
$setupArgs += "$root\src\Installer.cs"
$setupArgs += "$root\src\SetupAssemblyInfo.cs"
$setupArgs += "$root\src\Host.cs"
$setupArgs += "$root\src\Update.cs"
$setupArgs += "$root\src\Json.cs"
$setupArgs += "$root\src\MiniJson.cs"
$setupArgs += "$root\src\Corpus.cs"
$setupArgs += "$root\src\Library.cs"
$setupArgs += "$root\src\PayloadExt.cs"
# The payload, as a compressed manifest resource. Never as string literals -- this is the
# exact spot that blew csc's user-string heap once the payload grew (see New-PayloadZip).
$setupArgs += ("/resource:" + $payloadSetupZip + "," + $payloadResName)
# The history shards, as a compressed manifest resource. /resource: embeds the raw bytes --
# no base64, no UTF-16 doubling -- so 20 MB of shards costs ~20 MB of installer, not ~55 MB.
# The app build deliberately does NOT carry this: only the setup exe ever runs the
# --extract-to that unpacks it (see Update.cs), and ExtractShards no-ops when the resource
# is absent, so the app's own copy would be 20 MB of dead weight.
if (Test-Path $shardZip) {
  $setupArgs += ("/resource:" + $shardZip + ",Jigu.corpus.shards.zip")
  Write-Ok ("installer carries shards: " + [math]::Round((Get-Item $shardZip).Length/1KB,1) + " KB")
}
# The wizard reuses Host.cs, which references WebView2 types, so the same references apply.
$setupArgs += ("/reference:" + (Join-Path $wvDir "Microsoft.Web.WebView2.Core.dll"))
$setupArgs += ("/reference:" + (Join-Path $wvDir "Microsoft.Web.WebView2.WinForms.dll"))
$setupArgs += $genPath
# Same generated version file as the app build: SetupInfo.Version derives from it, so the
# "installed version" shown in Windows Settings can never drift from the binary's.
$setupArgs += $verPath
$setupOut = & $csc $setupArgs 2>&1
$setupOut | ForEach-Object { Write-Host "     $_" }
if ($LASTEXITCODE -ne 0) { throw ("installer compile failed, csc exit " + $LASTEXITCODE) }
Write-Ok ("installer: " + $setupPath + " (" + [math]::Round((Get-Item $setupPath).Length/1KB,1) + " KB)")

# ---------------------------------------------------------------- 7/7 update channel folder
# Everything the update channel needs, in one ASCII-named folder laid out exactly like the
# GitHub Release the app reads: CI uploads this directory verbatim as release assets, and
# locally it doubles as the "remote" for an offline end-to-end test.
Write-Step "7/7 assemble the update channel folder (dist\update)"
$updDir = Join-Path $dist "update"
if (Test-Path $updDir) { Remove-Item $updDir -Recurse -Force }
New-Item -ItemType Directory -Path $updDir -Force | Out-Null

Copy-Item (Join-Path $appDir "data_version.json") $updDir -Force
Copy-Item (Join-Path $appDir "corpus.json")       $updDir -Force
Copy-Item (Join-Path $res "labels.json")          $updDir -Force
Copy-Item (Join-Path $res "stopwords.json")       $updDir -Force

# Same asset name the release workflow publishes, so the local folder and the real Release
# are interchangeable -- which is what makes the offline simulation meaningful.
$updPkgName = "jigu-installer-v" + $version + ".exe"
Copy-Item $setupPath (Join-Path $updDir $updPkgName) -Force
$pkgHash = (Get-FileHash -LiteralPath $setupPath -Algorithm SHA256).Hash.ToLowerInvariant()

$av = [ordered]@{
  version   = $version
  url       = $updPkgName   # relative on purpose: resolved against the update source at runtime
  sha256    = $pkgHash
  notes     = ($APP_CH + " v" + $version)
  mandatory = $false
}
[System.IO.File]::WriteAllText((Join-Path $updDir "app_version.json"),
  ($av | ConvertTo-Json -Depth 4), (New-Object System.Text.UTF8Encoding($false)))
Write-Ok ("update channel ready: " + $updDir)
Get-ChildItem $updDir | Select-Object Name, @{n = "KB"; e = { [math]::Round($_.Length / 1KB, 1) } } | Format-Table -AutoSize

Write-Host ""
Write-Host "BUILD OK" -ForegroundColor Green
Write-Host ("  portable  : " + (Join-Path $appDir $exeName)) -ForegroundColor Green
Write-Host ("  zip       : " + $zip) -ForegroundColor Green
Write-Host ("  installer : " + $setupPath) -ForegroundColor Green
Write-Host ("  update    : " + $updDir + "  (upload these to the release / update channel)") -ForegroundColor Green
Get-ChildItem $appDir | Select-Object Name, @{n = "KB"; e = { [math]::Round($_.Length / 1KB, 1) } } | Format-Table -AutoSize



